//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_ware.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseEntities : DbContext
    {
        public WarehouseEntities()
            : base("name=WarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<atencion> atencion { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<envio> envio { get; set; }
        public virtual DbSet<Orden_servicio> Orden_servicio { get; set; }
        public virtual DbSet<Orden_trabajo> Orden_trabajo { get; set; }
        public virtual DbSet<tecnico> tecnico { get; set; }
    }
}
