//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_ware.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_trabajo
    {
        public int id_ot { get; set; }
        public int id_articulo { get; set; }
        public int id_tecnico { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_inicio { get; set; }
        public Nullable<System.DateTime> Fecha_termino { get; set; }
        public int id_atencion { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual tecnico tecnico { get; set; }
        public virtual atencion atencion { get; set; }
    }
}
